import { inventoryProductImagePublicUrl } from './productImages';
import { designImagePublicUrl } from './designImages';
import type { Order } from '../types/domain';

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    customer: 'Metro Athletics Club',
    item: 'Premium Cotton T-shirt (Black), Sport Mesh Jersey',
    lineItems: [
      { itemId: 'INV-001', name: 'Premium Cotton T-shirt (Black)', quantity: 36, designId: 'DSG-001' },
      { itemId: 'INV-004', name: 'Sport Mesh Jersey', quantity: 24, designId: 'DSG-003' },
    ],
    quantity: 60,
    status: 'In Production',
    date: '2026-04-28',
    amount: 6850.0,
    isCustom: true,
    designId: 'DSG-001',
    notes: 'Front-left chest print; roster PDF on file. Rush before city meet May 18.',
  },
  {
    id: 'ORD-002',
    customer: 'Northwind Café Collective',
    item: 'Pique Polo (Navy), Lint-Free Microfiber Shop Towels (50-pack)',
    lineItems: [
      { itemId: 'INV-003', name: 'Pique Polo (Navy)', quantity: 18, designId: 'DSG-002' },
      { itemId: 'INV-008', name: 'Lint-Free Microfiber Shop Towels (50-pack)', quantity: 4 },
    ],
    quantity: 22,
    status: 'Pending',
    date: '2026-05-02',
    amount: 3425.5,
    isCustom: true,
    designId: 'DSG-002',
    notes: 'Polos: left-chest embroidery tone-on-tone. Towels are shop merch—no imprint.',
  },
  {
    id: 'ORD-003',
    customer: 'Parcel & Post Mini Hub',
    item: 'Kraft Poly Mailers 10" × 13" (100-pack)',
    lineItems: [{ itemId: 'INV-009', name: 'Kraft Poly Mailers 10" × 13" (100-pack)', quantity: 10 }],
    quantity: 10,
    status: 'Ready for Pickup',
    date: '2026-05-05',
    amount: 1999.0,
    isCustom: false,
    notes: 'Retail counter pickup; VAT receipt required.',
  },
  {
    id: 'ORD-004',
    customer: 'Neon Nights Events Co.',
    item: 'Heavyweight Hoodie, Rechargeable LED Magnetic Work Light',
    lineItems: [
      { itemId: 'INV-005', name: 'Heavyweight Hoodie', quantity: 20, designId: 'DSG-004' },
      { itemId: 'INV-010', name: 'Rechargeable LED Magnetic Work Light', quantity: 8, designId: 'DSG-001' },
    ],
    quantity: 28,
    status: 'Designing',
    date: '2026-05-08',
    amount: 8920.0,
    isCustom: true,
    designId: 'DSG-004',
    notes: 'Hoodies: oversized back print + sleeve hit. Lights get small one-color wrap label.',
  },
];

export const MOCK_INVENTORY = [
  {
    id: 'INV-001',
    name: 'Premium Cotton T-shirt (Black)',
    category: 'Apparel',
    stock: 150,
    reorderLevel: 50,
    price: 5.50,
    imageUrl: inventoryProductImagePublicUrl('INV-001'),
  },
  {
    id: 'INV-002',
    name: 'Premium Cotton T-shirt (White)',
    category: 'Apparel',
    stock: 200,
    reorderLevel: 50,
    price: 5.20,
    imageUrl: inventoryProductImagePublicUrl('INV-002'),
  },
  {
    id: 'INV-003',
    name: 'Pique Polo (Navy)',
    category: 'Apparel',
    stock: 85,
    reorderLevel: 30,
    price: 8.50,
    imageUrl: inventoryProductImagePublicUrl('INV-003'),
  },
  {
    id: 'INV-004',
    name: 'Sport Mesh Jersey',
    category: 'Apparel',
    stock: 45,
    reorderLevel: 40,
    price: 12.00,
    imageUrl: inventoryProductImagePublicUrl('INV-004'),
  },
  {
    id: 'INV-005',
    name: 'Heavyweight Hoodie',
    category: 'Outerwear',
    stock: 120,
    reorderLevel: 25,
    price: 15.00,
    imageUrl: inventoryProductImagePublicUrl('INV-005'),
  },
  {
    id: 'INV-006',
    name: 'Plastisol Ink Starter Kit (CMYK)',
    category: 'Supplies',
    stock: 24,
    reorderLevel: 8,
    price: 48.0,
    imageUrl: inventoryProductImagePublicUrl('INV-006'),
  },
  {
    id: 'INV-007',
    name: 'Aluminum Screen Frame 20" × 24"',
    category: 'Equipment',
    stock: 18,
    reorderLevel: 6,
    price: 22.5,
    imageUrl: inventoryProductImagePublicUrl('INV-007'),
  },
  {
    id: 'INV-008',
    name: 'Lint-Free Microfiber Shop Towels (50-pack)',
    category: 'Supplies',
    stock: 40,
    reorderLevel: 12,
    price: 14.25,
    imageUrl: inventoryProductImagePublicUrl('INV-008'),
  },
  {
    id: 'INV-009',
    name: 'Kraft Poly Mailers 10" × 13" (100-pack)',
    category: 'Packaging',
    stock: 65,
    reorderLevel: 20,
    price: 19.99,
    imageUrl: inventoryProductImagePublicUrl('INV-009'),
  },
  {
    id: 'INV-010',
    name: 'Rechargeable LED Magnetic Work Light',
    category: 'Equipment',
    stock: 12,
    reorderLevel: 4,
    price: 32.0,
    imageUrl: inventoryProductImagePublicUrl('INV-010'),
  },
];

export const MOCK_FINANCIAL_RECORDS = [
  {
    id: 'FIN-001',
    date: '2026-04-28',
    type: 'Income',
    category: 'Screen Printing',
    description: 'Order ORD-001 — Metro Athletics Club (custom)',
    amount: 6850.0,
    linkedOrderId: 'ORD-001',
  },
  { id: 'FIN-002', date: '2026-05-01', type: 'Expense', category: 'Material', description: 'Plastisol & discharge ink restock', amount: 4200 },
  { id: 'FIN-003', date: '2026-05-01', type: 'Expense', category: 'Rent', description: 'Production bay rent — May', amount: 18500 },
  {
    id: 'FIN-004',
    date: '2026-05-02',
    type: 'Income',
    category: 'Embroidery & Garment',
    description: 'Order ORD-002 — Northwind Café Collective (custom)',
    amount: 3425.5,
    linkedOrderId: 'ORD-002',
  },
  { id: 'FIN-005', date: '2026-05-03', type: 'Expense', category: 'Inventory', description: 'Blank apparel & supplies PO', amount: 22800 },
  {
    id: 'FIN-006',
    date: '2026-05-05',
    type: 'Income',
    category: 'Retail POS',
    description: 'Order ORD-003 — Parcel & Post Mini Hub (walk-in)',
    amount: 1999.0,
    linkedOrderId: 'ORD-003',
  },
  { id: 'FIN-007', date: '2026-05-06', type: 'Expense', category: 'Utilities', description: 'Power & water — production floor', amount: 6400 },
  {
    id: 'FIN-008',
    date: '2026-05-08',
    type: 'Income',
    category: 'DTF / Specialty',
    description: 'Order ORD-004 — Neon Nights Events Co. (custom)',
    amount: 8920.0,
    linkedOrderId: 'ORD-004',
  },
];

export const MOCK_DESIGNS = [
  {
    id: 'DSG-001',
    name: 'Logo',
    category: 'Retro',
    imageUrl: designImagePublicUrl('DSG-001'),
    createdAt: '2026-01-12',
    tags: ['City', 'Vintage', 'Art'],
  },
  {
    id: 'DSG-002',
    name: 'Geometric Minimal',
    category: 'Abstract',
    imageUrl: designImagePublicUrl('DSG-002'),
    createdAt: '2026-02-03',
    tags: ['Simple', 'Modern'],
  },
  {
    id: 'DSG-003',
    name: 'Tropical Punch',
    category: 'Summer',
    imageUrl: designImagePublicUrl('DSG-003'),
    createdAt: '2026-02-20',
    tags: ['Bright', 'Floral'],
  },
  {
    id: 'DSG-004',
    name: 'Cyberpunk Neon',
    category: 'Tech',
    imageUrl: designImagePublicUrl('DSG-004'),
    createdAt: '2026-03-08',
    tags: ['Futuristic', 'Neon'],
  },
];

