/**
 * The PrintSync icon map — one source of truth for the name→glyph mapping.
 *
 * Key   = the export name call sites import (kept unchanged from lucide-react,
 *         so the swap touched import paths only).
 * Value = the Ionicons base name; the glyph file is `<value>-outline.svg` in
 *         the `ionicons` package.
 *
 * Shared by scripts/gen-icons.mjs (writes the module) and
 * scripts/gen-icon-preview.mjs (writes the review page).
 */
export const ICON_MAP = {
  Activity: 'pulse',
  AlertCircle: 'alert-circle',
  AlertTriangle: 'warning',
  ArrowRight: 'arrow-forward',
  Banknote: 'cash',
  BarChart3: 'bar-chart',
  Bell: 'notifications',
  Box: 'cube',
  Brain: 'bulb',
  Building2: 'business',
  Calendar: 'calendar',
  CalendarRange: 'calendar-clear',
  CheckCheck: 'checkmark-done',
  CheckCircle2: 'checkmark-circle',
  ChevronLeft: 'chevron-back',
  ChevronRight: 'chevron-forward',
  Clock: 'time',
  ClipboardList: 'clipboard',
  CreditCard: 'card',
  Download: 'download',
  Edit: 'create',
  Edit3: 'create',
  Eye: 'eye',
  FileText: 'document-text',
  Hammer: 'construct',
  History: 'time',
  Image: 'image',
  ImagePlus: 'image',
  Inbox: 'file-tray',
  KeyRound: 'key',
  LayoutDashboard: 'grid',
  LineChart: 'analytics',
  LoaderCircle: 'reload',
  Lock: 'lock-closed',
  Mail: 'mail',
  MessageSquare: 'chatbubble',
  Minus: 'remove',
  Monitor: 'desktop',
  Moon: 'moon',
  Package: 'archive',
  PackageCheck: 'bag-check',
  PackageSearch: 'receipt',
  Palette: 'color-palette',
  PenTool: 'brush',
  PanelLeft: 'menu',
  Phone: 'call',
  Plus: 'add',
  Printer: 'print',
  ReceiptText: 'receipt',
  RefreshCw: 'refresh',
  RotateCw: 'sync',
  ScrollText: 'document-text',
  Search: 'search',
  Settings: 'settings',
  Settings2: 'settings',
  Shield: 'shield',
  ShieldCheck: 'shield-checkmark',
  ShoppingBag: 'bag-handle',
  ShoppingCart: 'cart',
  Sun: 'sunny',
  Tag: 'pricetag',
  Trash2: 'trash',
  TrendingUp: 'trending-up',
  UploadCloud: 'cloud-upload',
  User: 'person',
  UserCircle: 'person-circle',
  Users: 'people',
  UserSquare: 'people-circle',
  Wallet: 'wallet',
  X: 'close',
};
