-- Branch scoping: tag every operational row with the branch that owns it.
--
-- This is Phase 2 of the two-branch rollout, and it runs immediately after
-- 20261002000200_branches.sql. Phase 1 created `branches` and made the *settings*
-- per-branch; **Phase 2 makes the data per-branch**. Nothing here enforces the
-- boundary yet — a query that forgets its `branch_id` filter still returns both
-- shops' rows until Phase 3 adds the predicates and the negative tests. That is
-- deliberate: this migration is additive and reversible, and the enforcement
-- migration can be reviewed on its own.
--
-- Plan of record: 0_never-push-this-dump-folder/printsync-two-branch-plan.md
--
-- ## What "scoped" means for each table, and why not all of them get a column
--
-- There are two ways a table can belong to a branch:
--
--   * **Owned** — the row *is* the thing (an order, a customer, a design), so it
--     carries `branch_id` directly. These are the tables staff list, create and
--     delete: `orders`, `sales_transactions`, `inventory_items`, `designs`,
--     `customers`, `suppliers`, `purchase_orders`, `operating_expenses`.
--
--   * **Inherited** — the row is a child whose parent already carries the branch,
--     so it gets NO column. Adding one would create a second copy of the same
--     fact, and the two copies can disagree: an `order_items` row could claim
--     Nasugbu while its `orders` row says Balayan. The parent is the single
--     source of truth, and every read of a child joins or filters through the
--     parent's id, which is already indexed. These tables are: `order_items`
--     (→ `orders`), `sales_transaction_items` (→ `sales_transactions`),
--     `payments` (→ `sales_transactions`), `order_payments` (→ `orders`),
--     `inventory_movements` (→ `inventory_items`).
--
-- The owner's rule — "stock is kept entirely separate per branch" — is satisfied
-- by the *owned* column on `inventory_items`: two branches can each have a ream
-- of A4 without either one's stock moving when the other sells. The movement log
-- inherits, so stock moved at Nasugbu is visible as Nasugbu's because the item
-- it belongs to is Nasugbu's.
--
-- ## Why nothing is unique-per-branch here
--
-- `inventory_items.sku` is `unique` globally today. Two branches legitimately
-- want their own `SKU-001`, but making that unique per branch is a *behaviour*
-- change that belongs with the enforcement work, and doing it now would silently
-- start rejecting a duplicate that the current catalogue already permits. Phase 3
-- converts `unique (sku)` to `unique (branch_id, sku)`. This migration adds the
-- column and nothing else, so a replay is a pure superset of the current schema.
--
-- ## Backfill
--
-- Every existing row is Balayan's. That is not an assumption: the shop has run
-- from one site, all 867 sales, 23 orders, 30 customers, 15 stock items and 6
-- suppliers in the live database were entered there, and Phase 1 assigned every
-- current profile to Balayan. Nasugbu starts with an empty book, which is what
-- the owner asked for ("Nasugbu's stock starts empty").

-- ─── 1. The eight owned tables ──────────────────────────────────────────────
--
-- `add column ... not null default ...` would be wrong here: a default would make
-- every *future* insert silently land in Balayan unless it opted out, which is
-- exactly the failure this whole phase exists to prevent. Instead the column is
-- added nullable, backfilled explicitly, then tightened to `not null` — so a
-- write that forgets its branch is rejected by the database rather than filed in
-- the wrong shop. (Phase 3 makes the API always send one; Phase 2 makes the
-- database refuse to invent one.)

alter table public.orders
  add column if not exists branch_id uuid references public.branches(id) on delete restrict;
alter table public.sales_transactions
  add column if not exists branch_id uuid references public.branches(id) on delete restrict;
alter table public.inventory_items
  add column if not exists branch_id uuid references public.branches(id) on delete restrict;
alter table public.designs
  add column if not exists branch_id uuid references public.branches(id) on delete restrict;
alter table public.customers
  add column if not exists branch_id uuid references public.branches(id) on delete restrict;
alter table public.suppliers
  add column if not exists branch_id uuid references public.branches(id) on delete restrict;
alter table public.purchase_orders
  add column if not exists branch_id uuid references public.branches(id) on delete restrict;
alter table public.operating_expenses
  add column if not exists branch_id uuid references public.branches(id) on delete restrict;

-- Backfill to Balayan by code, not by a hard-coded uuid. The id is generated by
-- `gen_random_uuid()` in Phase 1 and differs between a local replay and the live
-- project, so a literal would work exactly once.
update public.orders              set branch_id = (select id from public.branches where code = 'BAL') where branch_id is null;
update public.sales_transactions  set branch_id = (select id from public.branches where code = 'BAL') where branch_id is null;
update public.inventory_items     set branch_id = (select id from public.branches where code = 'BAL') where branch_id is null;
update public.designs             set branch_id = (select id from public.branches where code = 'BAL') where branch_id is null;
update public.customers           set branch_id = (select id from public.branches where code = 'BAL') where branch_id is null;
update public.suppliers           set branch_id = (select id from public.branches where code = 'BAL') where branch_id is null;
update public.purchase_orders     set branch_id = (select id from public.branches where code = 'BAL') where branch_id is null;
update public.operating_expenses  set branch_id = (select id from public.branches where code = 'BAL') where branch_id is null;

-- Now nothing may be branch-less. This is the statement that fails loudly if the
-- backfill above missed a row, which is why it is separate rather than bundled
-- into the `add column`.
alter table public.orders             alter column branch_id set not null;
alter table public.sales_transactions alter column branch_id set not null;
alter table public.inventory_items    alter column branch_id set not null;
alter table public.designs            alter column branch_id set not null;
alter table public.customers          alter column branch_id set not null;
alter table public.suppliers          alter column branch_id set not null;
alter table public.purchase_orders    alter column branch_id set not null;
alter table public.operating_expenses alter column branch_id set not null;

comment on column public.orders.branch_id is
  'The branch that owns this order. Set on create from the creator''s profile; never moved between branches (there is no inter-branch transfer).';
comment on column public.sales_transactions.branch_id is
  'The branch that rang up this sale. Set by create_transaction_with_payment from the caller''s branch.';
comment on column public.inventory_items.branch_id is
  'The branch whose shelf holds this stock. Two branches may each hold their own copy of the same product; stock never moves between them.';
comment on column public.designs.branch_id is
  'The branch whose catalogue this design belongs to. Nasugbu''s catalogue starts as a copy of Balayan''s and diverges from there.';
comment on column public.customers.branch_id is
  'The branch this customer belongs to. Customers are not shared between branches.';
comment on column public.suppliers.branch_id is
  'The branch this supplier belongs to.';
comment on column public.purchase_orders.branch_id is
  'The branch this (reserved, not-yet-wired) purchase order belongs to.';
comment on column public.operating_expenses.branch_id is
  'The branch that incurred this expense. A branch''s books only count its own.';

-- ─── 2. Indexes ─────────────────────────────────────────────────────────────
--
-- Every list in Phase 3 filters on `branch_id`, and every foreign key is indexed
-- in this schema (see 20260921000700_index_foreign_keys.sql). A `branch_id` with
-- no index turns each branch-filtered list into a sequential scan of every
-- branch's rows combined — i.e. the new predicate would make the *common* query
-- slower than the unscoped one it replaces.

create index if not exists orders_branch_created_idx
  on public.orders (branch_id, created_at desc);
create index if not exists sales_transactions_branch_created_idx
  on public.sales_transactions (branch_id, created_at desc);
create index if not exists inventory_items_branch_name_idx
  on public.inventory_items (branch_id, name);
create index if not exists designs_branch_created_idx
  on public.designs (branch_id, created_at desc);
create index if not exists customers_branch_name_idx
  on public.customers (branch_id, name);
create index if not exists suppliers_branch_name_idx
  on public.suppliers (branch_id, name);
create index if not exists purchase_orders_branch_idx
  on public.purchase_orders (branch_id);
create index if not exists operating_expenses_branch_date_idx
  on public.operating_expenses (branch_id, expense_date desc);

-- Phase 1 added `profiles.branch_id` as a foreign key but no index for it. Every
-- FK in this schema is indexed (see 20260921000700_index_foreign_keys.sql), and
-- this one is the FK the *other* eight columns above all point through: a branch
-- cannot be deleted while any profile still references it, and without this index
-- that check scans every row of `profiles`. The migration-replay gate flagged it
-- as the one remaining "foreign key with no usable index", which is how it was
-- found rather than by reading. It sits in the Phase 2 migration because that is
-- the file that completes the branch schema, even though the column is Phase 1's.
create index if not exists profiles_branch_id_idx
  on public.profiles (branch_id);

-- ─── 3. Per-branch document numbering ───────────────────────────────────────
--
-- Today a document's reference is `PS-` + the last 8 characters of its uuid,
-- derived in the browser (`OrdersTable.tsx`). That is fine for one shop and
-- useless for two: the number carries no branch and cannot be read aloud on a
-- phone to the other branch. The owner accepted `BAL-0001` / `NAS-0001`.
--
-- The number is generated *in the database*, inside the same statement that
-- creates the row, using a per-branch counter. Two properties matter and both are
-- why this is not computed from `count(*)`:
--
--   * **It never repeats**, even under concurrency. `count(*) + 1` gives two
--     orders the same number when two cashiers save at once; a sequence does not.
--   * **It never goes backwards.** Deleting order 7 must not make the next order
--     reuse "7". A counter that only moves forward gives an auditor a stable
--     reference.
--
-- The counter lives in `branch_counters`, one row per (branch, document type), so
-- orders and sales can number independently. `next_document_number` takes a row
-- lock for the duration of its own statement, so two concurrent creators in the
-- same branch are serialised on that one row and cannot draw the same value.

create table if not exists public.branch_counters (
  branch_id uuid not null references public.branches(id) on delete restrict,
  document_type text not null check (length(btrim(document_type)) > 0),
  last_number integer not null default 0 check (last_number >= 0),
  primary key (branch_id, document_type)
);

alter table public.branch_counters enable row level security;

-- Read-only to authenticated clients, like every other table in this schema; all
-- writes go through the service role via `next_document_number`.
create policy "authenticated users can read branch counters"
on public.branch_counters for select
to authenticated
using (true);

grant select on public.branch_counters to authenticated;
grant select, insert, update, delete on public.branch_counters to service_role;

comment on table public.branch_counters is
  'Monotonic per-branch document counters. One row per (branch, document type). Read by next_document_number, which is the only writer.';

-- Allocates the next number for one branch and document type, and returns it.
--
-- `insert ... on conflict do update ... returning` is one atomic statement. The
-- `update` inside the conflict clause takes a row lock, so a second caller blocks
-- until the first commits and then increments from the committed value — the two
-- cannot both read `n` and both return `n + 1`. This is why the counter is a row
-- and not a Postgres `sequence`: a sequence is global to the column and cannot be
-- partitioned per branch without one sequence per branch, which is DDL at
-- runtime.
create or replace function public.next_document_number(
  p_branch_id uuid,
  p_document_type text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  allocated integer;
  branch_code text;
begin
  if p_branch_id is null then
    raise exception 'A branch is required to allocate a document number';
  end if;

  -- Lock the branch row itself so the code read below cannot race a rename.
  select code into branch_code
  from public.branches
  where id = p_branch_id
  for share;

  if branch_code is null then
    raise exception 'Branch % does not exist', p_branch_id;
  end if;

  insert into public.branch_counters (branch_id, document_type, last_number)
  values (p_branch_id, btrim(p_document_type), 1)
  on conflict (branch_id, document_type)
    do update set last_number = public.branch_counters.last_number + 1
  returning last_number into allocated;

  -- Zero-padded to four digits, matching the `BAL-0001` shape the owner accepted.
  -- Past 9999 the padding simply widens (`BAL-10000`); a print shop will not
  -- reach five digits in a year, but wrapping would be worse than a wider number.
  return branch_code || '-' || lpad(allocated::text, 4, '0');
end;
$$;

revoke all on function public.next_document_number(uuid, text) from public, anon, authenticated;
grant execute on function public.next_document_number(uuid, text) to service_role;

-- The documents that get a human reference. Both columns are nullable: they are
-- written by the creating RPC going forward, and a replay of an already-created
-- row does not retroactively renumber it (the number was never allocated for it,
-- and inventing one now would break the "never goes backwards" guarantee because
-- the counter would have to jump past every existing row's absent number).
alter table public.orders
  add column if not exists reference text;
alter table public.sales_transactions
  add column if not exists reference text;

comment on column public.orders.reference is
  'Human-readable document number (`BAL-0001`). Null for orders created before Phase 2; those remain addressable by uuid.';
comment on column public.sales_transactions.reference is
  'Human-readable receipt number (`BAL-0001`). Null for sales created before Phase 2.';

-- A branch cannot issue the same reference twice, and the unique index is what
-- makes that a database guarantee rather than a convention. Partial, because
-- every pre-Phase-2 row is null and nulls would otherwise all collide... except
-- they do not: a plain unique index already treats nulls as distinct. The
-- predicate is kept to document that only allocated numbers are covered.
create unique index if not exists orders_reference_key
  on public.orders (reference) where reference is not null;
create unique index if not exists sales_transactions_reference_key
  on public.sales_transactions (reference) where reference is not null;

-- ─── 4. Seed Nasugbu's catalogue as a copy of Balayan's ─────────────────────
--
-- The owner chose "a copy" for the catalogue. Designs are copied as rows so
-- Nasugbu can edit or delete its own without touching Balayan's — a shared row
-- would mean one branch deleting a design the other still sells. The image is
-- referenced by URL, so a copy points at the same stored file; that is intended,
-- the artwork is the same artwork, and only the *listing* is per-branch.
--
-- Guarded on Nasugbu having no designs at all, so re-running is a no-op and a
-- later Nasugbu that has curated its own catalogue is never re-seeded.
insert into public.designs (name, category, image_url, asset_type, asset_size_bytes, branch_id, created_by)
select d.name, d.category, d.image_url, d.asset_type, d.asset_size_bytes,
       (select id from public.branches where code = 'NAS'),
       d.created_by
from public.designs d
where d.branch_id = (select id from public.branches where code = 'BAL')
  and not exists (
    select 1 from public.designs n
    where n.branch_id = (select id from public.branches where code = 'NAS')
  );

-- Stock is deliberately NOT copied. The owner was explicit: "Nasugbu's stock
-- starts empty." Nasugbu's staff enter their own opening counts, which is the
-- only way the counts are true for what is physically on Nasugbu's shelves.

-- ─── 5. Tighten profile membership ──────────────────────────────────────────
--
-- Phase 1 left `profiles.branch_id` nullable because the auth row is created
-- before the profile row, so a profile can briefly not exist — but a profile that
-- *exists* without a branch is an account that can log in and see nothing or
-- everything, depending on how Phase 3 fails. Now that every operational table
-- demands a branch, an account without one has no coherent place in the system,
-- so the column is tightened here, in the same migration that gives the data its
-- branch. The insert path was made to always write one in Phase 1's service
-- changes; this makes the database refuse the alternative.
alter table public.profiles
  alter column branch_id set not null;

-- ─── 6. Grants for the new column are implicit ──────────────────────────────
--
-- Columns added to a table are covered by that table's existing table-level
-- grants, so `select/insert/update/delete on public.orders to service_role`
-- already includes `branch_id`. No new grant is needed, and adding one would be
-- noise. `branch_counters` is the only genuinely new table and is granted above.
